### ISSUE TITLE
오타 제보

### ISSUE THREAD

**Issue by WooilJeong** [mrchypark/djk-collect-data-with-r#2]
https://mrchypark.github.io/djk-collect-data-with-r/#47
https://mrchypark.github.io/djk-collect-data-with-r/#49

PUST -> POST
마이너하긴 하지만 오타 제보합니다.

**Comment by mrchypark** [comment]
감사합니다. 수정하였습니다. :)

https://github.com/mrchypark/djk-collect-data-with-r/commit/3d7538e7b2f89210b0f34e050cbfbb3db0d800de
